const actionTypes = {
  ALL_HOUSES: 'ALL_HOUSES',
  SINGLE_HOUSE: 'SINGLE_HOUSE',
  SIGN_UP: 'SIGN_UP',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',
  AUTHENTICATE: 'AUTHENTICATE',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  FAVOURITES: 'FAVOURITES',
  ADD_FAVOURITES: 'ADD_FAVOURITES',
  REMOVE_FAVOURITES: 'REMOVE_FAVOURITES',
  FETCH_FAVOURITES: 'FETCH_FAVORITES',
};

export default actionTypes;
