export const ActionTypes = {
  SET_HOUSES: 'SET_HOUSES',
  SELECTED_HOUSE: 'SELECTED_HOUSE',
  REMOVE_SELECTED_HOUSE: 'REMOVE_SELECTED_HOUSE',

  SET_FAVOURITES: 'SET_FAVOURITES',
  SELECTED_FAVOURITE: 'SELECTED_FAVOURITE',
  REMOVE_SELECTED_FAVOURITE: 'REMOVE_SELECTED_FAVOURITE',

  SET_USERS: 'SET_USERS',
  SELECTED_USER: 'SELECTED_USER',
  REMOVE_SELECTED_USER: 'REMOVE_SELECTED_USER',
};

export const Jacktrial = {
  SET_JACK: 'SET_JACK',
};
